---
services:
  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    network_mode: bridge
    environment:
      - TS_AUTHKEY=tskey-auth-<FULL_KEY>
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - ${PWD}/tailscale-nginx/state:/var/lib/tailscale
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
      - sys_module
    restart: unless-stopped
  nginx:
    build:
      context: .
      dockerfile: ./Dockerfile
    #image: nginx:v2
#    volumes:
#      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
    #network_mode: bridge
    #ports:
    #- "8006:8006"
    #- "8007:8007"
    #entrypoint: bash -c "/root/run_socat.sh &"
